[project]
name = "mcp-ml-workflow-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.23.3",
    "pandas>=2.3.3",
]
